version: "3.2"
services:
  wibot:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: .Dockerfile
    volumes:
      - .:/home/app # Убедитесь, что путь правильный
    command: "node app.js"